[package]
name = "sol-loan-agreement"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-program = "2.0.5"
borsh = "1.5.1"
thiserror = "1.0.31"

[lib]
crate-type = ["cdylib", "lib"]
